version: '3'

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    env_file: 
      - .env  # Aquí se hace referencia a tu archivo .env
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: wordwave_owner
      POSTGRES_PASSWORD: aUdDPt9X7ZQs
      POSTGRES_DB: wordwave
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
